# Server Config
server:
  port: 8500
  tomcat:
    max-http-form-post-size: 128MB

# Spring Config
spring:
  application:
    name: fileloader-api
  profiles:
    active: local
  servlet:
    multipart:
      enabled: false
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mariadb://localhost:3306/fileloader
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:postgresql://localhost:5432/fileloader
#    driver-class-name: org.postgresql.Driver
    username: root
    password: Password123!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# HDFS Config
hadoop:
  hdfs:
    username: hdfs
    base_uri: hdfs://localhost:9000
  config:
    library_path: E:\dev\hadoop-3.0.0

# Logging:
logging:
  level:
    com.geoffkflee: DEBUG
    root: INFO
