# Server Config
server:
  port: 8500
  tomcat:
    max-http-form-post-size: 128MB

# Spring Config
spring:
  application:
    name: fileloader-api
  profiles:
    active: local
  servlet:
    multipart:
      enabled: false
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mariadb://localhost:3306
    username: root
    password: Password123!
    driver-class-name: org.mariadb.jdbc.Driver

# HDFS Config
hdfs:
  username: test_hadoop_user
  base_uri: hdfs://hdfs-local

# Logging:
logging:
  level:
    com.geoffkflee: DEBUG
    root: INFO
